version: 2
models: 
  - name: dim_movies
    description: "Dimension table for movies"
    columns:
      - name: movie_id
        description: "Unique identifier for each movie"
        tests:
          - unique
          - not_null
      - name: movie_title
        description: "Title of the movie"
        tests:
          - not_null
      - name: genres_array
        description: "Array of genres associated with the movie"
      - name: genres
        description: "Pipe-separated string of genres"
  
  - name: dim_genome_tags
    description: "Dimension table for genome tags"
    columns:
      - name: tag_id
        description: "Unique identifier for each genome tag"
        tests:
          - unique
          - not_null
      - name: tag_name
        description: "Name of the genome tag"
        tests:
          - not_null

  - name: dim_users
    description: "Dimension table for users"
    columns:
      - name: user_id
        description: "Unique identifier for each user"
        tests:
          - unique
          - not_null
  - name: fact_ratings
    description: "Fact table for user ratings"
    columns:
      - name: user_id
        description: "Unique identifier for each user"
        tests:
          - not_null
      - name: movie_id
        description: "Unique identifier for each movie"
        tests:
          - not_null
          - relationship:
              to: ref('dim_movies')
              field: movie_id 
      - name: rating
        description: "Rating given by the user to the movie"
        tests:
          - not_null
      - name: rating_timestamp
        description: "Date when the rating was given"
        tests:
          - not_null
  
  - name: fact_genome_scores
    description: "Fact table for genome scores"
    columns:
      - name: movie_id
        description: "Forigen key to fim_movies"
        tests:
          - not_null
      - name: tag_id
        description: "Unique identifier for each genome tag"
        tests:
          - not_null
      - name: relevance_score
        description: "Relevance score of the genome tag for the movie"
        tests:
          - not_null
